<?php
global $URL_PATH;
\dawfony\Ti::extend("view/mainview.phtml");
\dawfony\Ti::startBlock("content");
?>
<main>
    <form action="<?= $URL_PATH ?>/login" onsubmit="return validarformulario()" method="POST">
        <div class="form-group row">
            <label for="cliente" class="col-12 col-md-2 col-form-label h2">Cliente :</label>
            <div class="col-12 col-md-10">
                <input type="text" class="form-control" id="cliente" name="cliente" value="<?= $login ?>" placeholder="Ingresa nombre cliente">
            </div>
        </div>
        <div class="form-group row">
            <label for="email" class="col-12 col-md-2 col-form-label h2">Password :</label>
            <div class="col-12 col-md-10">
                <input type="password" class="form-control" id="password" name="password" placeholder="Ej.1234">
                <span style="color:red"><b><?= $error_msg ?></b></span>
            </div>
        </div>
        <div class="form-group row">
            <label for="email" class="col-12 col-md-2 col-form-label h2">E-mail :</label>
            <div class="col-12 col-md-10">
                <input type="email" class="form-control" id="email" name="email" placeholder="Ej.ejemplo@gmail.com">
            </div>
        </div>
        <div class="form-group row">
            <label for="email" class="col-12 col-md-2 col-form-label h2">Direccion de envio :</label>
            <div class="col-12 col-md-10">
                <input type="text" class="form-control" id="direccion" name="direccion" placeholder="Ej.Calle Libertad, Nº4, 3ºA">
            </div>
        </div>
        <img src="<?= $URL_PATH ?>/assets/fotos/visa.jpg" width="80">
        <div class="form-group row">

            <label for="email" class="col-12 col-md-2 col-form-label h2">Tarjeta de credito:</label>
            <div class="col-12 col-md-10">
                <input type="number" class="form-control" id="tarjeta" name="tarjeta" onchange="validarTarjeta()" placeholder="Visa">
                <span style="color:red"><b id="errorTarjeta"></b></span>
                <span style="color:blue"><b id="visaCorrecto"></b></span>
                <br>
                <div class="input-group mb-3">
                    <label for="inputState">Mes</label>&nbsp;
                    <select id="inputState" class="form-control">
                        <option selected>01</option>
                        <option>02</option>
                        <option>03</option>
                        <option>04</option>
                        <option>05</option>
                        <option>06</option>
                        <option>07</option>
                        <option>08</option>
                        <option>09</option>
                        <option>10</option>
                        <option>11</option>
                        <option>12</option>
                    </select>
                    &nbsp;<label for="inputState">Año</label>&nbsp;
                    <select id="inputState" class="form-control">
                        <option selected>2020</option>
                        <option>2021</option>
                        <option>2022</option>
                        <option>2023</option>
                        <option>2024</option>
                        <option>2025</option>
                        <option>2026</option>
                        <option>2027</option>
                    </select>
                    &nbsp;<input type="text" class="form-control" id="cvv" name="cvv" placeholder="CVV" min="3" max="3">
                </div>
            </div>
        </div>
        <button type="submit" class=" btn btn-primary btn-block" id="procesar-compra">Enviar</button>
    </form>
</main>
<?php
\dawfony\Ti::endBlock();
\dawfony\Ti::endExtend();
?>