<?php
global $URL_PATH;
\dawfony\Ti::extend("view/mainview.phtml");
\dawfony\Ti::startBlock("content");
?>


<!-- ********************** listado ******************************************* -->

<div class="container" id="lista-productos">

  <div class="card-deck mb-3 text-center">
    <div class="row">
      <?php $cuenta = 0;
      foreach ($productos as $producto) : ?>
        <div class="card mb-4 shadow-sm">
          <div class="card-header">
            <h4 class="my-0 font-weight-bold"><?= $producto->nombre ?></h4>
          </div>
          <div class="card-body">
            <img src="<?=$URL_PATH?>/assets/fotos/tablas/<?= $producto->img ?>" width="100" height="400" class="card-img-top">
            <h1 class="card-title pricing-card-title precio"><span class=""><?= $producto->precio ?></span>&euro;</h1>

            <ul class="list-unstyled mt-3 mb-4">
              <li></li>
              <li>Tipo: <?= $producto->descripcion ?></li>
              <li>Flex: <?= $producto->flex ?></li>

            </ul>
            <a href="javascript:void(0)" onclick="compra(<?= $producto->id ?>)" class="btn btn-block btn-primary agregar-carrito" data-id="<?= $producto->id ?>">Comprar</a>
          </div>
        </div>
      <?php endforeach ?>
    </div>


    <!-- ********************** Modal ******************************************* -->
    <script>
      function compra(id) {
        console.log("Realizamos compra de Prodcto con id " + id);
        // Esto es jquery, copiado de la documentación de bootstrap.
        $('#productosModal').modal('show'); // mostrar div oculto de manera modal. 
        comprarProducto(id);
      }
    </script>


    <div class="modal fade" id="productosModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
      <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">Producto añadido correctamente al carrito </h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <div class="container-fluid">
              <div class="row">
                <img id="imagen" width="70" >
                <strong>
                  x
                  <span id="contadorCantidad">
                  </span>
                </strong>
                &nbsp;&nbsp;- &nbsp;&nbsp;<p id="nombre"></p> &nbsp;&nbsp;=
                &nbsp;
                  <p id="precio"></p>&euro;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
               <b> TOTAL:&nbsp;<b>
                <b><p id="totalprecio"></p><b>
            </div>
          </div>
          <div class="modal-footer">
            <a href="<?= $URL_PATH ?>/realizarCompra" type="button" class="btn btn-secondary" >Realizar Compra</a>
            <a href="<?= $URL_PATH ?>" type="button" class="btn btn-primary">Seguir Comprando</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>




<!-- Paginacion -->
<!-- Hay algo que no hace bien la paginacion, se queda la ruta fija y añade la ruta de paginacion otra vez -->
<nav aria-label="...">
  <ul class="pagination">
    <li class="page-item <?= ($pagina  <= 1 ? "disabled" : "") ?>">
      <a class="page-link" href="<?= $ruta . ($pagina - 1) ?>" tabindex="-1" aria-disabled="true">Anterior</a>
    </li>
    <?php
    for ($i = 1; $i <= $numpaginas; $i++) {
    ?>

      <li class="page-item ">
        <a class="page-link" href="<?= $ruta ?><?= $i ?>"><?= $i ?></a>
      </li>

    <?php
    }
    ?>
    <li class="page-item <?= ($pagina + 1 > $numpaginas ? "disabled" : "") ?>">
      <a class="page-link" href="<?= $ruta . ($pagina + 1) ?>" aria-disabled="true">Siguiente</a>
    </li>
  </ul>
</nav>


<?php
\dawfony\Ti::endBlock();
\dawfony\Ti::endExtend();
?>