<?php
// necesitamos la trayectoria de la URL para formar las rutas:
global $URL_PATH;

?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="robots" content="noindex,nofollow">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
    <script src="<?= $URL_PATH ?>/js/cesta.js"></script>
    <script src="<?= $URL_PATH ?>/js/comprar.js"></script><!--  -->
    <script src="<?= $URL_PATH ?>/js/incrementarCantidades.js"></script>
    <script src="<?= $URL_PATH ?>/js/validar.js"></script>
    <script src="<?= $URL_PATH ?>/js/validarTarjeta.js"></script>
    <script>
        var URL_PATH = "<?= $URL_PATH ?>"; // Pasamos el URL_PATH de php a Javascript.
    </script>
    <script>
        var articulos = <?= $data ?>;
    </script>
    <style>
        input[type=number]::-webkit-outer-spin-button,
        input[type=number]::-webkit-inner-spin-button {
            -webkit-appearance: none;
            margin: 0;
        }
        input[type=number] {
            -moz-appearance: textfield;
        }
    </style>

    <title>
        <?php \dawfony\Ti::startBlock("title"); ?>
        Tiendaw
        <?php \dawfony\Ti::endBlock(); ?>
    </title>
    <?php /* Bootstrap.CDN */ ?>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <?php /* Font awesome CDN */ ?>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <?php /* Animate.css CDN */ ?>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css">


    <?php /*Para añadir lineas al head desde las plantillas derivadas*/ ?>
    <?php \dawfony\Ti::startBlock("head"); ?>
    <?php \dawfony\Ti::endBlock(); ?>

</head>

<body class="container">
    <div class="jumbotron jumbotron-fluid">
        <div class="text-center myfont">
            <h1><img src="<?= $URL_PATH ?>/assets/fotos/imagenPrincipal.png" width="200"><img src="<?= $URL_PATH ?>/assets/fotos/logo.png">&nbsp;&nbsp;<img src="<?= $URL_PATH ?>/assets/fotos/imagenPrincipal2.png" width="150"></h1>
            <center>
                <img src="<?= $URL_PATH ?>/assets/fotos/promotores/burton.jpg" width="50">
                <img src="<?= $URL_PATH ?>/assets/fotos/promotores/capita.jpg" width="50">
                <img src="<?= $URL_PATH ?>/assets/fotos/promotores/calavera.jpg" width="50">
                <img src="<?= $URL_PATH ?>/assets/fotos/promotores/gnu.png" width="50">
                <img src="<?= $URL_PATH ?>/assets/fotos/promotores/salomon.jpg" width="50">
            </center>
            <div class="header-mini-cart  pull-left open" id="formCompra">
                <img src="<?= $URL_PATH ?>/assets/fotos/carrito.jpeg" class="nav-link dropdown-toggle img-fluid" height="70px" width="70px" href="javascript:void(0)" onclick=" verCarrito()" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span><?= $data ?> Articulo(s)</span>
                <div class="dropdown-menu shopping-cart-content pull-right">
                    <div class="shopping-cart-items">

                        <div class="total lg-left">
                            <table>
                                <tbody id="productosCesta" class="lg-right">

                                </tbody>
                                <tr>
                                    <td></td>
                                    <td>Total:</td>
                                    <td><b class="precioTotalincrement"><?= $sumaTotal ?>&euro;</b></td>
                                </tr>
                                <tr>
                                    <td></td>
                                    <td><?php if ($data != 0) : ?>
                                            <a href="<?= $URL_PATH ?>/realizarCompra" class="btn btn-dark btn-read pull-right">Pagar</a>
                                        <?php else : ?>
                                            <a href="javascript:void(0)" class="btn btn-dark btn-read pull-right">Pagar</a>
                                        <?php endif; ?>
                                    </td>
                                    <td><a href="<?= $URL_PATH ?>/vaciarCesta" class="btn btn-warning btn-read pull-right">Vaciar Cesta</a></td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>




    <?php \dawfony\Ti::startBlock("content"); ?>


    <?php \dawfony\Ti::endBlock(); ?>
    <footer class="rounded p-4 mt-2 text-center bg-light myfont">
        © <?= date("Y") ?> 2ºDAW
    </footer>
</body>



</html>